### ISSUE TITLE
No support for 3.24

### ISSUE THREAD

**Issue by theyer** [theychx/WorkspaceSwitcherWrapAround#1]
As stated, this is not updated for 3.24. Can you please add 3.24 to the metadata json?

**Comment by theychx** [comment]
Have you tested the extension on 3.24? If it works then I'll be happy to update. Debian is still on 3.22, so I haven't gotten around to testing this myself.

**Comment by theyer** [comment]
Yep works perfectly on 3.24.2 with Arch.
