### ISSUE TITLE
Gnome 41.x Support

### ISSUE THREAD

**Issue by jorp** [theychx/WorkspaceSwitcherWrapAround#10]
I'm not sure what changes (if any) need to be made, but a quick (and potentially dirty) workaround can be achieved by modifying the shell-version array in `~/.local/share/gnome-shell/extensions/workspace-switch-wraparound@theychx.org/metadata.json` to include '41' like so:

```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "When switching workspaces, going down from the bottom workspace switches to the top workspace. Likewise, up from the top workspace goes to the bottom workspace.",
  "name": "Workspace Switch Wraparound",
  "shell-version": [
    "3.30",
    "3.34",
    "3.32",
    "3.36",
    "3.38",
    "40",
    "41"
  ],
  "url": "https://github.com/theychx/WorkspaceSwitcherWrapAround",
  "uuid": "workspace-switch-wraparound@theychx.org",
  "version": 7
}
```
then log out and back in.

**Comment by eneiluj** [comment]
Thanks a lot for the hint.
This also works for Gnome 42.

**Comment by theychx** [comment]
Updated extension uploaded to extensions.gnome.org. Thanks!
