### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by 2k16daniel** [theychx/WorkspaceSwitcherWrapAround#15]
Hello , is there a posibility for a support to gnome 45?

**Comment by julien-nc** [comment]
#16 adds support for Gnome 45. You can manually edit files in `~/.local/share/gnome-shell/extensions/workspace-switch-wraparound@theychx.org` to try it at home and confirm it works or not :grin: .

**Comment by theychx** [comment]
#16 merged!
