### ISSUE TITLE
Can you make it work with horizontal-workspaces extension?

### ISSUE THREAD

**Issue by paulodeleo** [theychx/WorkspaceSwitcherWrapAround#9]
Currently not working on Ubuntu 20.04 with [horizontal-workspaces](https://extensions.gnome.org/extension/2141/horizontal-workspaces/) extension installed.

**Comment by theychx** [comment]
The extension has been [abadoned](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/commit/d7c8a5d193553f8d82616ed57ab9c28d5a6734ef) by its developer, so I'm afraid not.
